# baselines/tool_backends/nodes/front_layer_extraction_layerd.py
from __future__ import annotations
from typing import Dict, Any
from pathlib import Path
from PIL import Image
import cv2

from ..state import GraphState
from ..reducers import (
    r_save_artifact,
    r_update_front, r_set_mask_path, r_set_img_slot, r_pack_state,
    r_abort_to_verify_sequence
)
from ..utils import resolve_img
from ._common import _pop_current_action, _call_tool, _bump_next_or

SEG_MASK_MIN_PX = 8  # common pixel threshold shared with segmentation

def node(state: GraphState) -> Dict[str, Any]:
    act, upd0 = _pop_current_action(state)

    pieces = [upd0]

    # Select the input image (priority: base)
    img_sel = resolve_img("front_extract", state)
    args = {"image_path": img_sel["path"]}

    # LayerD front extraction
    out = _call_tool("LayerD_Front", args, state)  # {"front_rgb","front_mask"}

    front_rgb = (out or {}).get("front_rgb")
    front_mask = (out or {}).get("front_mask")

    # If front_rgb is missing: go straight to the planner
    if not front_rgb or not Path(front_rgb).exists():
        return r_abort_to_verify_sequence(
            state,
            node="layerd_front",
            error_msg="layerd_front failed: no front rgb image generated by layerd_front",
            details={"front_rgb": [front_rgb]},
        )

    # Save artifact
    extra_rgb, saved_rgb = r_save_artifact(front_rgb, "layerd_front", "front", state)
    pieces.append(extra_rgb)
    
    '''
    saved_mask = None
    if front_mask and Path(front_mask).exists():
        extra_mask, saved_mask = r_save_artifact(front_mask, "layerd_front", "front", state)
        pieces.append(extra_mask)
    '''
        
    # === Guard: check mask pixel area (common threshold: fail if under 8px) ===
    area = 0
    '''
    if saved_mask:
        try:
            m = cv2.imread(saved_mask, cv2.IMREAD_GRAYSCALE)
            if m is not None:
                area = int((m > 0).sum())
        except Exception:
            area = 0
    '''
    if front_mask and Path(front_mask).exists():
        try:
            m = cv2.imread(front_mask, cv2.IMREAD_GRAYSCALE)
            if m is not None:
                area = int((m > 0).sum())
        except Exception:
            area = 0
    else:
        # If front_mask is missing, treat area as 0 and handle as failure
        area = 0

    if area < SEG_MASK_MIN_PX:

        return r_abort_to_verify_sequence(
            state,
            node="layerd_front",
            error_msg=f"layerd_front front layer extraction failed: front layer segmentation mask area too small (area={int(area)})",
            details={"mask_area": int(area), "threshold": int(SEG_MASK_MIN_PX)},
        )

    # Success path: register the front slot/metadata/mask path
    try:
        W, H = Image.open(saved_rgb).size
    except Exception:
        W = H = None

    pieces += [
        r_set_img_slot("front", saved_rgb, coord_id="front", W=W, H=H, state=state),
        r_update_front(saved_rgb, front_mask, {"to_base": "identity"}, state=state),
        r_set_mask_path(front_mask),
        _bump_next_or(state, "tool_sequence_plan"),
    ]

    return r_pack_state(state, *pieces)
